version: '3.3'

services:

    traefik:
        image: "traefik:2.3"
        container_name: "traefik"
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./conf:/etc/traefik
        - ./conf/acme.json:/acme.json
        networks:
            - traefik_proxy
        ports:
        - 80:80
        - 443:443
        - 8080:8080