version: '3'

networks:
  frontend:

volumes:
  vol-gitlab-config:
  vol-gitlab-logs:
  vol-gitlab-data:

services:
  watchtower:
    image: v2tec/watchtower:latest
    command: --cleanup --schedule "0 0 0 * * *"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: "localhost"
    ports:
      - "8082:22"
      - "80:80"
    networks:
      - frontend
    volumes:
      - vol-gitlab-config:/etc/gitlab
      - vol-gitlab-logs:/var/log/gitlab
      - vol-gitlab-data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add gitlab.rb configuration here, each on its own line.
        # See: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
        external_url 'http://localhost'
        letsencrypt['enable'] = false
        # Configure headers for outgoing email.
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_display_name'] = 'GitLab'
        # Send outgoing email via the SMTP container:
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "mail"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_tls'] = false
        # Limit backup lifetime to 7 days (604800 seconds):
        gitlab_rails['backup_keep_time'] = 604800

  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - frontend
  
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    depends_on:
    - gitlab
    volumes:
    - ./config/gitlab-runner:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock

